### ISSUE TITLE
URI datatype

### ISSUE THREAD

**Issue by kcoyle** [dcmi/dcap#70]
Phil points out in a [comment](https://github.com/dcmi/dcap/issues/68#issuecomment-678250144) on #68 that ALL of the xsd datatypes are literal types, by definition. That means that xsd:anyURI is a literal type, as:

"https://www.dublincore.org/"^^xsd:anyURI

I see two options (more if others occur to me) which I give separately below for voting.

**Comment by kcoyle** [comment]
Option 1: require RDF (value) type for URIs

In this option, the valueDataType column is limited to XSD-defined types, all of which are literals, including xsd:anyURI. To specify that the value will be a non-literal URI, that must be done in the "RDF node/value type" column.

|RDF value type|Value datatype|
|----|----|
|URI| |

Advantage: URI is indicated in only one place

Disadvantage: Profile creators have two places to put values and may not understand the difference

**Comment by kcoyle** [comment]
Option 2: Define a value datatype for "URI"

This requires only one column for (probably) the majority of uses, and puts all value types in a single column. 

|RDF value type|value datatype|
|----|----|
|URI|URI|

Advantage: For less sophisticated users the URI as a value is just another type of value, as evidenced in Sinopia where a value can be either a literal or a URI. This fits with the kinds of URIs many profiles use, which are seen as lists with identifiers.
Disadvantage: If the RDF value type column is used there will be duplication in the profile table; also, it requires us to develop a non-xsd element for URI.

In the case of "URI or string", how would this be coded in the table?

|RDF value type|value datatype|
|----|----|
|?? |URI or string|

Note that this *could* be presented as an OWL:annotationProperty, but we are not assuming OWL. I suppose this brings up the question of whether the OWL property types would help us out here, and whether we think they could correspond to actual needs.

**Comment by tombaker** [comment]
Hmm - I thought we had been talking about four value-related columns:

* `value_rdf_type`, with one of: Literal, Nonliteral, URI, BNode - the one we had wanted to de-emphasize for non-RDF users.
* `value_datatype`, "[any datatype defined in the xsd list](https://github.com/dcmi/dcap/issues/68#issue-679289442)" which [I suggested](https://github.com/dcmi/dcap/issues/68#issuecomment-675877429) be called `literal_value_datatype`
* `constraint_type`, with a starter set of types such as URI stem and Date, which is what I (perhaps mistakenly) thought the [Doodle poll](https://doodle.com/poll/vz7snn4i8xexgfg4) was about
* `constraint_value`, for the value of the actual picklist, URI stem, or whatever, the type of which is defined by `constraint_type`

I had thought we might get by without a separate column for `literal_value_datatype` if literal value datatype URI were one of the starter types for `constraint_type`, such that the corresponding value under `constraint_value` would be `xsd:string`, `xsd:date`, or some other literal value datatype, but I thought we were collectively leaning towards putting literal value type URIs in a separate column. 

On the other hand, it is quite possible that I have gotten my wires crossed about this...! (And I'm looking forward to reading the minutes on this point!)

**Comment by kcoyle** [comment]
@tombaker We are indeed talking about four columns. To me it seems clear that xsd:string is a datatype. If we have xsd:string as a constraint value then we would need yet another column to give, for example, a pick list. The xsd elements are defined in their own [documentation](https://www.w3.org/TR/xmlschema11-2/#built-in-datatypes) as datatypes and they are familiar as datatypes for those coding in XML. I don't think we should or can try to redefine them as constraints on datatypes.

That they are defined as literal data types for RDF is clearly not universally understood (in this group, it was only Phil who was approaching the value datatype column in this way, AFAICT) and I don't know that we want to disallow non-literal values in the column. *Note: while the RDF concepts define these node types, they are not terms in the RDF schema vocabulary with the exception of rdf:Literal, which is a class. It is only ShEx that defines and uses these as part of its vocabulary.* So although we can call them RDF node types, the only use of them in code that I'm aware of is in the [ShEx node kind constraints.](http://shex.io/shex-semantics/index.html#nodeKind). If people do think of node types at all I suspect they think in terms of the OWL property types, which are much more diffuse in the community. 

The question here is where we define URI as a value type. I am not in favor of having separate columns for literal types and non-literal types. I am also not in favor of defining a column for RDF node type as I do not think that the ShEx node kind constraints are generalized beyond ShEx. We could consider whether we wish to support ShEx to the extent of adding a ShEx Node Kind column as an extension.

**Comment by philbarker** [comment]
Another option: merge the two columns that relate to the types of value that are allowed in instance data, to hold values such as:
entity - URIref
entity - BNODE
entity [- either]
literal [- any]
literal - xsd:string
literal - xsd:date
literal - xsd:anyURI
literal -....

Advantage: avoids accidental use of xsd:anyURI with non-literals
Disadvantage: brings the RDF right in to the face of people who may not be familiar with it.

FWIW, I think that people creating RDF profiles are going to face a little RDF.

**Comment by tombaker** [comment]
> That they are defined as literal data types for RDF is clearly not universally understood (in this group, it was only Phil who was approaching the value datatype column in this way, AFAICT) and I don't know that we want to disallow non-literal values in the column. 

I had always understood 'datatype', as used in our discussions, to mean the RDF datatype for a literal value and thought the only question was whether they would be listed in their own column (eg, 'value_datatype') or handled using the 'constraint_type/constraint_value' columns. In my `csv2shex` code, I treated RDF datatype as a possible "constraint type" and built in a validity check to verify that if "RDF datatype" was specified as 'constraint type', then a URI (or prefixed URI) [must be given as the corresponding value for 'constraint_value'](https://csv2shex.readthedocs.io/en/latest/normalizations/datatypes.html). Accordingly, this would be legal:

|prop_id|constraint_type|constraint_value|
|----|----|----|
|dc:date|RdfDatatype|xsd:string|

but _NOT_:

|prop_id|constraint_type|constraint_value|
|----|----|----|
|dc:date|RdfDatatype|string|

In the Dublin Core context, what we are calling an RDF datatype was called a [Syntax Encoding Scheme](https://www.dublincore.org/specifications/dublin-core/abstract-model/), the URI of which was associated (only) with value strings.

> If we have xsd:string as a constraint value then we would need yet another column to give, for example, a pick list. 

That is one reason I prefer that we keep them in a separate column -- so that other value constraints can be specified.

IMO this is a known limitation in the design of our template: the four-column approach to constraining values places an upper limit on the number of constraints that can be specified for a value in a statement. But that limit is higher with four columns than with three.

> The xsd elements are defined in their own [documentation](https://www.w3.org/TR/xmlschema11-2/#built-in-datatypes) as datatypes and they are familiar as datatypes for those coding in XML. I don't think we should or can try to redefine them as constraints on datatypes.

I'm not sure what you mean. As I see it, XSD URIs could be listed either directly 'value_datatype', or they could be listed under 'constraint_value' where the 'constraint_type' is [Rdf]Datatype. In either case, they are constraints on the (literal) value.

> *Note: while the RDF concepts define these node types, they are not terms in the RDF schema vocabulary with the exception of rdf:Literal, which is a class. It is only ShEx that defines and uses these as part of its vocabulary.* So although we can call them RDF node types, the only use of them in code that I'm aware of is in the [ShEx node kind constraints.](http://shex.io/shex-semantics/index.html#nodeKind). If people do think of node types at all I suspect they think in terms of the OWL property types, which are much more diffuse in the community. 

I'm not sure I see a problem here. [RDF Concepts 1.1](https://www.w3.org/TR/rdf11-concepts/) says there can be three types of nodes in an RDF graph: IRIs, literals, and blank nodes. ShEx does add a fourth ("nonliteral") as the union of IRIs and blank nodes. So these are RDF things, and ShEx creates four keywords for them for use in ShEx syntax, just as our DCAP CSV model would create four keywords for use in drop-down menus.

> The question here is where we define URI as a value type. 

I thought we had decided to keep 'value_rdf_type' (renamed), so:

|prop_id|value_rdf_type|
|---|---|
|dc:creator|URI|
|dc:date|Literal|

> I am not in favor of having separate columns for literal types and non-literal types. 

In the example above, both are handled in the same column. If, in addition, one wants to specify that RDF datatype URI xsd:date be used, one could do this with 'constraint_type' and 'constraint_value':

|prop_id|value_rdf_type|constraint_type|constraint_value|
|---|---|---|---|
|dc:creator|URI|||
|dc:date|Literal|RdfDatatype|xsd:string|

To minimize references RDF for the sake of non-expert users, one could call this LiteralDatatype and this could be expressed as:

|prop_id|constraint_type|constraint_value|
|---|---|---|
|dc:creator|||
|dc:date|LiteralDatatype|xsd:string|

and any processing software could infer from the above that the value_rdf_type is Literal.

@philbarker I agree and think we should not go too far to shield users from RDF. For example, the template should not be confusing for RDF users.

**Comment by briesenberg07** [comment]
I believe that we *could* express everything in three columns for value types and constraints...

|prop_id|value_rdf_type|constraint_type|constraint_value|
|---|---|---|---|
|dct:creator|iri|iriStem|http://viaf.org|
|dct:date|literal|datatype|xsd:date|
|dct:contributor|nonliteral|valueEntityShape|\@contributor|
|dct:created|literal|regex|^\d{4}-\d{2}-\d{2}$|

...that is, *without* a value_datatype column. This could be expressed as a "datatype" `constraint_type` with corresponding `constraint_value` [some datatype IRI].

***But...*** 
...this presents a challenge when a profile creator wishes to express both a datatype *and* another constraint (say, a regex for a literal value) for a value. This is certainly conceivable.
(And perhaps we are worried about the use of datatype constraints that don't fit the given `value_rdf_type`?)

Would it be possible to express multiple `constraint_type`-`constraint_value` pairs for a given `prop_id`??

**Comment by tombaker** [comment]
@briesenberg07 I think your approach can work, and it summarizes where I had until this week thought we were heading, including treatment of the RDF datatype URI [as a constraint value](https://csv2shex.readthedocs.io/en/latest/normalizations/datatypes.html).

I had thought we'd keep entity shape references in a separate column but see no technical reason they could not be treated like any other constraint value, as you do. (I think we should reconsider whether we should distinguish shape references with punctuation `@` but that is a different issue.)

As you point out, collapsing these things into four columns puts a lower limit on the number of constraints a profile creator can define for a value, though this is an inherent limitation for a model with a fixed number of non-repeatable columns. One way around that could be to offer additional, more-explicit columns for advanced users (e.g., 'literal_rdf_datatype', 'entity_shape_reference'). (FWIW I still like the idea of keeping 'entity_shape_reference', or 'shape_ref' in a column of its own.)

The main objection I think one might make to this model is that it provides no obvious place to say that the value should be a date without declaring testable constraints such as  'xsd:date' and '^\d{4}-\d{2}-\d{2}$'. A simple indication that the value is intended to be read as a date could perhaps be put into an annotation. Might that be handled with a less formal way to say that the value is a date ('value_type_label')?

|prop_id|value_rdf_type|constraint_type|constraint_value|value_type_label|
|---|---|---|---|---|
|dct:date|literal|datatype|xsd:date||
|dct:created|literal|regex|^\d{4}-\d{2}-\d{2}$||
|dct:modified||||Date|

**Comment by kcoyle** [comment]
Isn't your value type label the property label that we already have? And your constraint type is a mix of datatypes and constraint types. With this you do not have a way to have a date with a regex (or some other constraint). We had worked that out previously by having a data type column and constraint/constraint type.

It seems we are getting quite far from our previously agreed columns, which doesn't seem like a good thing. Could we get back on track? Here's what we have agreed on to date:

entityID,entityLabel,propertyID,propertyLabel,mandatory,repeatable,valueType,valueDataType,valueConstraint,entityShapeReference,annotation,

**Comment by johnhuck** [comment]
> Another option: merge the two columns that relate to the types of value that are allowed in instance data, to hold values such as:
> entity - URIref
> entity - BNODE
> entity [- either]
> literal [- any]
> literal - xsd:string
> literal - xsd:date
> literal - xsd:anyURI
> literal -....

This is the direction that I was thinking in as well. I find it confusing to start to think of the xsd datatypes as constraints, as I think Tom is thinking. One use case I can think of that isn't entirely covered with Phil's suggestion is when someone wants to say that either an IRI or a literal is acceptable. I can point to the Samvera MODS to RDF recommendation as an example. 

There might be a couple of ways to handle this, though:

1. no value in this column means any datatype
2. we create a value type for "any" that encompasses all of the other values
3. we determine that `literal [-any]` (above) would cover that case, since it includes xsd:anyURI

**Comment by kcoyle** [comment]
Tom's example is easily accommodated in our agreed columns:

|prop_id|label|value_rdf_type|datatype|constraint_type|constraint|
|---|---|---|---|---|---|
|dct:date|Date|Literal|xsd:date|||
|dct:created|Create date|literal|xsd:date|regex|^\d{4}-\d{2}-\d{2}$
|dct:modified|Date modified|literal|xsd:date||

**Comment by philbarker** [comment]
@johnhuck good point, your solutions are good too (thanks). There are two other options:

4. allow multiple entries for type of value, e.g.: xsd:anyURI | entity-URI (but this may remove the possibility of a drop-down list in the user interface)
5. in some cases it is possible to have two statements about the same property, each with different value (doesn't work if you want the property to be mandatory but don't care which type a value is)

**Comment by kcoyle** [comment]
What I think was proposed during the meeting:

|prop_id|label|value_rdf_type|datatype|constraint_type|constraint|
|---|---|---|---|---|---|
|dct:date|Date|Literal|xsd:date|||
|dct:created|Create date|literal|xsd:date|regex|^\d{4}-\d{2}-\d{2}$
|dct:modified|Date modified|literal|xsd:date||
|dct:creator|Author|Entity| | URIstem|http://viaf.org
|dct:contributor|Contributor|EntityOrLiteral| | |
|dct:rights|Rights|Entity|BNODE||

The RDF types would be: Literal, Entity, or EntityOrLiteral.
Note that these correspond generally to OWL:dataProperty, OWL:objectProperty, and OWL:annotationProperty

In terms of node types, ShEx has: iri, bnode, literal, nonliteral

SHACL has: sh:NodeKind: sh:BlankNode, sh:IRI, sh:Literal sh:BlankNodeOrIRI, sh:BlankNodeOrLiteral and sh:IRIOrLiteral.

**Comment by johnhuck** [comment]
@kcoyle Yes, this is what I proposed, as a variation on Phil's suggestion above -- essentially splitting the items in his list at the dash (' - '), so the prefix (Literal or Entity) is in its own column, and adding "EntityOrLiteral" as a third option to cover that use case.

The only proviso I would add is that if Entity or Literal appeared without a datatype value in the next column, I think you would have to infer that this meant `Entity [- either]` or `Literal [-any]` and so in the example above the dct:creator row (as presented above) could not have URIstem in the constraint_type column without also having `URIRef` (Phil's formulation) in the datatype column.

**Comment by tombaker** [comment]
I have several objections to redefining value_rdf_type [as above](https://github.com/dcmi/dcap/issues/70#issuecomment-680946989):
* "Entity" is not a node type in RDF, and it is not used this way in either ShEx or SHACL. Shouldn't our terminology at least be in line with RDF, ShEx, and SHACL?
* I thought we established on the call that "datatype", in this RDF context, means "literal datatype". BNode is not a literal datatype and should be listed under "value_rdf_type" (as both ShEx and SHACL do).
* I note that neither ShEx nor SHACL has a term that express "EntityOrLiteral". I thought we were talking about handling this by allowing two value RDF types to be indicated, eg 'literal nonliteral' (or in SHACL terms 'iri literal blanknode').

**Comment by tombaker** [comment]
@johnhuck Re: "could not have URIstem in the constraint_type column without also having URIRef (Phil's formulation) in the datatype column". I started to write some checks precisely to catch such consistencies, eg, [constraint_type of URIStem without a constraint_value that is a URI](https://csv2shex.readthedocs.io/en/latest/normalizations/validate_uri.html).

**Comment by kcoyle** [comment]
@tombaker What I gave above is the second proposal, based on Phil and John's interpretations. Remember that at the end of the call we looked at [John's interpretation](https://github.com/dcmi/dcap/issues/70#issuecomment-680893566) and [Phil's additions](https://github.com/dcmi/dcap/issues/70#issuecomment-680910867) and I said I would try to mock it up to show what was meant. This is an *alternate* proposal to the original set of columns. It is possible that we should not name the column "datatype" if that evokes a restriction to xsd: types. We could name it "value type", as it was in the beginning before we got examples using that column for the RDF node types.

As for aligning with RDF, ShEx and SHACL - each one is different, so we would have to pick. But in addition there are the property types in OWL (object/data/annotation) which are widely used and understood, and there is also the common "thing/string" statement. I think we should use terms that people will understand, and perhaps could allow synonyms. That is, if we decide to go with this suggestion.

**Comment by tombaker** [comment]
@kcoyle Allowing synonyms might be a good way to handle some of these. I do not think it is necessary to align perfectly with ShEx or SHACL or anything else - any conversion program, such as the one I am working on, should be able to handle the equivalences. 

The OWL classes are widely understood, but they have to do with how the properties are defined, but vocabulary definitions are somewhat orthogonal to instance data (and their corresponding application profiles). I take the point that the different types of properties support different inferences about the nature of values, but inferencing should really have no role here. The profile should just say whether values are expected to be URIs or literals (or both). I don't think you are suggesting otherwise but just want to make sure we agree.

One alternative I thought we were discussing on the call was to have a value type column with Date as one of a controlled list of starter values, then we would say in the definition of Date that it is defined in accordance with the XML schema definition.  That is quite different from using the prefixed URI xsd:date which, as far as I can tell, is used only in RDF (not in XML) and only as an RDF datatype URI.

**Comment by johnhuck** [comment]
@kcoyle and @tombaker : I wouldn't focus on the column labels as they are now. They aren't right, I agree. Essentially, the first column are broad, non-normative categories that organize the items in the second column, which would be a mix of Literal datatypes and the 2 varieties of entities (IRIs and BNodes). Phil introduced the term "entities", which I think will speak to non-specialists intuitively.

**Comment by tombaker** [comment]
@kcoyle I think we decided at some point (perhaps on a call?) that `valueDataType` means datatype in the RDF sense and must therefore be a URI. If so, could we perhaps close this one?

**Comment by kcoyle** [comment]
This has been resolved with separate columns for valueNodeType and valueDatatype.
