### ISSUE TITLE
Should we use the term "application profile"?

### ISSUE THREAD

**Issue by analice1pt** [dcmi/dcap#8]
I have to say I do not especially like the term "application profile" because it may lead someone to think about a given specific application as argued by Heery and Patel [1]. It seems to me that we are thinking about "metadata profiles" and not necessarily "application profiles", i.e., we may not have in mind a particular application. Does it make sense to you?

And why am I raising this issue? Because I think that a "metadata application profile" is one kind of "metadata profiles" we may have. My question is: should we use "metadata profile" instead of "application profile"?

[1] http://www.ariadne.ac.uk/issue25/app-profiles

**Comment by paulwalk** [comment]
I have always quite liked the Heery & Patel definition for the reason you give here - that it grounds the ‘profile’ in some concrete use-case.

I agree that we don’t need to take any view on any particular application in this work, but I think it is a useful constraint to be able to assume that the ‘profile’ is aimed at some application, however broad that is.

**Comment by analice1pt** [comment]
> No dia 22/04/2019, às 19:15, Paul Walk <notifications@github.com> escreveu:
> 
> I have always quite liked the Heery & Patel definition for the reason you give here - that it grounds the ‘profile’ in some concrete use-case.
> 
> I agree that we don’t need to take any view on any particular application in this work, but I think it is a useful constraint to be able to assume that the ‘profile’ is aimed at some application, however broad that is.
> 
> 

I am not sure of that, Paul. I think sometimes a metadata profile only expresses a view of a community. Sometimes it is not intended for a particular application. It’s a kind of an abstract approach to what might be needed by a given community. A view of some people that many times is not materialized in any specific application. I think DCMI had some metadata profiles like this in the past, right? I think we had one for Education, another one for Government.

An application implementing such a profile will probably have to cut or add properties and change constraints. It will need a specific profile that will include at least part of the first profile. It will need its specific application profile. If we call everything "application profile", we won’t have a term for *real* application profiles.

Best regards,

Ana

**Comment by kcoyle** [comment]
Again, to reflect some decisions of the [W3C DXWG group](https://www.w3.org/2017/dxwg/wiki/Main_Page) but definitly _not_ saying that we should follow that, they decided to simply use *profile* - not application profile or metadata profile. There has also been quite a bit of pushback on any use of the term _metadata_, preferring data instead. (I'm fine with metadata, but that's a reflection of my background.) 

My feeling is that _profile_ alone is much too ambiguous since it's used for many different things.

[Application profile](https://en.wikipedia.org/wiki/Application_profile) comes out of programming, and to me is too specific to express the idea of interoperability (because being aimed at a single application doesn't sound very interoperable). I consider interoperability a big factor in today's profiles. I agree with Ana that there are degrees of profiling, and I think we are going to have to address this: allowing degrees of specificity while still considering them to meet our definition of "whatever-we-call-it" profile.

**Comment by nishad** [comment]
I prefer to use 'data profiles' or 'metadata profile' to an extent. Data Profile is self-explanatory as metadata is the de-facto part of data in the context and philosophy of models like RDF.

Application, Profile and Application Profile are somewhat confusing terminology for communities including computer science or software engineering. And they have a distinct and different definition from the metadata concepts.

Since we talk about interoperability, the data can be applied in different applications as well as LOD expands the possibilities. So in my understanding, data is no more application specific.

**Comment by nishad** [comment]
I prefer to use 'data profiles' or 'metadata profile' to an extent. Data Profile is self-explanatory as metadata is the de-facto part of data in the context and philosophy of models like RDF.

Application, Profile and Application Profile are somewhat confusing terminology for communities including computer science or software engineering. And they have a distinct and different definition from the metadata concepts.

Since we talk about interoperability, the data can be applied in different applications as well as LOD expands the possibilities. So in my understanding, data is no more application specific.

**Comment by paulwalk** [comment]
I would like to defend the use of the word ‘application’ in this phrase. The explicit indication that the ‘profile’ will have some ‘application’ steers us towards considering how the profile may be implemented. I believe that this is a very healthy aspect.

Note that the ‘application’ in this sense can be quite broad - and may even be used to indicate a general purpose information exchange application.

I think this is about the difference between modelling in the abstract, and designing to some purpose.

I also have a preference for ‘metadata’, rather than ‘data’.

So, I guess I am voting to keep ‘application profile’ as a useful label. To misquote George Box:

> All labels are wrong, but some are useful....

:-)

**Comment by tombaker** [comment]
I can live with any of the variants proposed here but lean to the @paulwalk position for two reasons:
* I agree that "application" can be quite broad ("government")
* "application" usefully emphasizes the aspect of "design for purpose".
* in the Dublin Core community we have called them APs for twenty years, so the term permeates our historical record and website.

I agree with @kcoyle that "profile", on its own, is too ambiguous.

I vaguely recall having this same discussion a _long_ time ago.  If I recall, "interoperability profile" was even one of the contenders. I am planning to write a paper about something I am tempted to call "mapping profiles", which I would describe as a type of application profile.  I have written papers where I establish "application profiles" as the topic and thereafter refer to them as "profiles". I see no real problem with using a somewhat looser terminology when talking about APs in particular contexts, while retaining "application profile" as the generic term.

**Comment by analice1pt** [comment]
I think that sometimes we do not design for the purpose of applications, even considering the term in a broad sense. It is increasingly frequent to just wanting to release data. For instance, statistical data about healthcare services, or electoral data. In many cases the objective is just  to make that data available as Linked Open Data (LOD) without further issues. In these cases, there is no application in mind, whether narrow or broad. The goal is just to release the data in a semantically interoperable way so that it can be used and reused by *any* application, whatever are its functional requirements. It seems to me that the only purpose behind the design of those profiles is maximizing semantic interoperability. In my view, this kind of profiles might well be called data profiles, for instance. No functional requirements, no applications in mind.

In my mind it is clear that we have profiles of *different nature* and I think we should acknowledge that. I do agree with @tombaker  in his third reason, however: changing terms after 20 years may not be a good idea. The term has already been assimilated by the community and a change may result in more confusion. In the case we decide to keep the term, I think that we need to do a historical contextualization and we need to acknowledge that there are different natures of profiles. This is important in conceptual terms.

**Comment by nishad** [comment]
My curiosity is with the abbreviation as well. **MAP** is not as established as Metadata Application Profiles. If there is any easy to say, but a unique short form, something like **MdAP** (Emdap)? ShEx is catchy, comfortable and goes well with repetitive usage.

**Comment by nichtich** [comment]
I agree with tombaker, the term "application profile" is more or less established. "(meta)data constraints profile" might be used as explanation or alternative label. Anyway it should be made clear that the profiles are about data. Instead of discussing only the preferred label better provide name, aliases, short definition and full definition together.

**Comment by kcoyle** [comment]
I'd add to "the profiles are about data" something like "the profiles are about data, definitions, creation, validation and reuse". @tombaker often says (I'm paraphrasing you here, Tom) that profiles are the consensus of a community, and they aid a community in reaching consensus about their data. There is a human element that is a reason that profiles are needed and that makes them work.

**Comment by tombaker** [comment]
It looks to me like:
* we generally accept, if only reluctantly, the established term "application profile" 
* we are comfortable with a rather free use of aliases (like "metadata profile" or "mapping profile") that acknowledge the diverse nature and uses of profiles
* we see a need for historical contextualization and explanation (e.g., "profiles are about data")

Interesting that ["Dublin Core application profile"](http://www.dublincore.org/specifications/dublin-core/singapore-framework/) has not come up.  The Singapore Framework was intended by its authors as a generic model for application models for use in the DC community but not necessarily based on The Dublin Core per se, so DC-15 was deliberately de-emphasized.  Understandably, however, many people read the name as meaning "Profiles of Dublin Core" (i.e., of the fifteen elements).  I was among those who argued for "DCMI Abstract Model" instead of "Dublin Core Abstract Model" precisely to avoid this sort of confusion (because nobody needs an abstract model for a flat set of fifteen elements).  In writing, therefore, I tend to refer to application profiles "in the Dublin Core style".

**Comment by analice1pt** [comment]
@kcoyle, could you explain better what you mean by "the profiles are about data, definitions, creation, validation and reuse"? In particular, when you say "creation" are you referring to the creation of the profiles? And what about reuse? Are you referring to reuse of data? Or am I misunderstanding your words?

**Comment by kcoyle** [comment]
Ana, I mean creation and reuse of the data. If you look at the [draft vocabulary](https://github.com/dcmi/dcap/blob/master/schemaList.csv) I did (and that may be entirely re-written by this group!), it includes properties for usage instructions, descriptions, etc. that are intended to help humans create and understand the data. It also has min/max to define cardinality of descriptions and statements, and various constraints on values. These can be acted on by programs but also have information for humans. You can say that it's all about the "data" but I prefer being clear that there are a variety of activities that we wish to support, like data creation.

**Comment by analice1pt** [comment]
"You can say that it's all about the "data" but I prefer being clear that there are a variety of activities that we wish to support, like data creation."

@kcoyle , I like and support that view.

**Comment by nichtich** [comment]
@kcoyle the draft vocabulary is too low-level, I'd prefer to start without specific mapping to RDF in terms of natural language, come to a controlled vocabulary and add URIs later.

**Comment by kcoyle** [comment]
We are not limiting our work to RDF, although it is hard to point to potential usable terms that are NOT exposed as RDF ontologies. I agree that we should back up and start with the basic structure, which is also where I started, but could lead us elsewhere. That should be a different issue. I'll open one.

**Comment by philbarker** [comment]
Picking up on  @kcoyle 

> it's all about the "data" but I prefer being clear that there are a variety of activities that we wish to support, like data creation.

and @tombaker's [comment](https://github.com/dcmi/dcap/issues/15#issuecomment-490120490) on another issue, 

> To me, APs are about things "in the data".  

if only there were a term that meant "data about data"...

**Comment by GordonDunsire** [comment]
fwiw, the new RDA introduces the following terminology:

**application profile**: A specification of the metadata that is used in an application. A specification may include the entities, elements, and vocabulary encoding schemes that are used, and the mandatory and repeatable status of elements.
**metadata description set:** One or more metadata statements that describe and relate individual instances of one or more RDA entities.
**metadata statement**: A piece of metadata that assigns a value to an RDA element that describes an individual instance of an RDA entity.
**metadata work**: A work that is a metadata statement or a metadata description set.

The context of these terms and definitions is wider than LOD and the audience is non-technical. RDA chose the terminology to reflect DCAM rather than traditional cataloguing concepts like "record" and "resource". The ambiguity of "description" is now constrained within RDA to "metadata description set".

**Comment by kcoyle** [comment]
@GordonDunsire I'm not clear on the "metadata description set" and how it differs from the application profile. Can you give some short examples? I guess I also have to ask about "metadata work" - would a profile be metadata work, or does that refer to what we formerly called a "record"? If the latter, then would a temporary graph, such as the output of a SPARQL query, also be a metadata work? Thanks.

**Comment by RDATech** [comment]
@kcoyle and others

Apologies - To avoid confusion with other projects, I'm signed on under a new username; please ignore the "GordonDunsire" username. 

A metadata description set is instance data. They are associated with an application profile that specifies only properties of RDA entities.

An example of a metadata description set is a "record" in a bibliographic database; the fields are properties specified by an application profile, such as the MARC 21 manual and encoding format, or a row in an RDBMS table for an RDA entity/class.

A metadata work is a type of RDA Work. This allows a metadata statement or set of statements to be described using RDA properties and entities to provide data provenance: the creator of a metadata work may be a cataloguer Person or Corporate Body; the carrier type of a Manifestation of a catalogue "record" may be a card, online resource, etc.

Most use cases would not record a metadata work unless it was embodied in at least one manifestation: that is, the metadata description set must be recorded on a non-transitory carrier. In RDF, an RDA metadata description set is a named graph, so "temporary" graphs would not be described unless, for example, they were frozen as snapshots in a web archive - that is, assigned a name.

An application profile is treated as just a Work in RDA: it is not "data about data"; it is a specification of data. An application profile work may be related to a creator agent, expressed in multiple content formats (i.e. description languages), and embodied in multiple carrier formats (e.g. csv spreadsheet, doc table). Of course, an RDA description of an application profile would, itself, be a metadata work, etc.

**Comment by tombaker** [comment]
@kcoyle Great discussion from last year, which I think we have resolved. Close?

**Comment by kcoyle** [comment]
Yes, we do.
